헤더 네비게이션 메뉴 드롭다운 형식으로 변경 및 채팅 페이지 UI 구현
woowacourse-teams/2021-drop-the-code pull request #312
Opened 2021-09-04 13:54 UTC by shinsehantan

- 헤더 네비게이션 메뉴를 프로필 아이콘 하위 드롭다운 메뉴 형식으로 변경
- 채팅 페이지 UI 구현
- mock 데이터 활용
- 추후 채팅 리스트 조회, 현재 채팅 조회 api 연동 및 웹소켓 사용하여 채팅 기능 구현 예정

2021-09-04 13:54 UTC, jh8579 commented
Can one of the admins verify this patch?

2021-09-06 00:51 UTC, seojihwan requested changes
몇가지 코멘트 수정해주시면 감사하겠습니다!

2021-09-06 00:51 UTC, seojihwan commented on frontend/src/components/Chatting/ChattingList.tsx
> +  });
```suggestion
  chattingList.sort((a, b) => b.createdAt - a.createdAt))
```

2021-09-06 00:51 UTC, seojihwan commented on frontend/src/components/Chatting/ChattingList.tsx
> +                  )}
[date constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date)

date객체의 메서드를 활용할 수 있을 것 같은데 어떤가요?

2021-09-06 00:51 UTC, seojihwan commented on frontend/src/components/Chatting/CurrentChatting.tsx
> +import RightSingleMessage from "./RightSingleMessage";
절대경로를 사용하지 않은 이유가 있나요?

2021-09-06 00:51 UTC, seojihwan commented on frontend/src/components/Chatting/CurrentChatting.tsx
> +  });
마찬가지로 정렬만 필요하다면 위의 코멘트를 참고해볼까요?

2021-09-06 00:51 UTC, seojihwan commented on frontend/src/components/Chatting/CurrentChatting.tsx
> +            }
네트워크 응답에 상대방 정보가 추가된다면 바뀔로직일까요?

2021-09-06 00:51 UTC, seojihwan commented on frontend/src/components/Chatting/CurrentChatting.tsx
> +      </FormProvider>
👍

2021-09-06 00:51 UTC, seojihwan commented on frontend/src/components/DropDownMenu/DropDownMenu.tsx
> +      <LineDivider></LineDivider>
self closing을 활용해보는 것은 어떨까요?

2021-09-06 00:51 UTC, seojihwan commented on frontend/src/components/Header/Header.tsx
> +            onClick={() => setDropdownOpen(!dropdownOpen)}
내부적으로 clsoe open을 제어하고 있는데 외부에서 다시 제어하는 이유는 무었일까요?

2021-09-06 00:51 UTC, seojihwan commented on frontend/src/components/MenuItemButton/MenuItemButton.tsx
> +const MenuItemButton = ({ contents, onClick, children, ...props }: Props) => {
onClick이벤트를 전달해주어야 하는 이유가 있나요?

2021-09-06 00:51 UTC, seojihwan commented on frontend/src/components/shared/Button/Button.tsx
> +    box-shadow: ${({ theme, hover }) => (hover ? theme.common.boxShadow.primary : "")};
빈 스트링보다는 밑에서사용하고있는 none이 더 좋지 않을까요??

2021-09-06 00:51 UTC, seojihwan commented on frontend/src/components/shared/Button/Button.tsx
> +      active ? theme.components.button[themeColor].activeBg : ""};
마찬가지입니다!

2021-09-06 00:58 UTC, seojihwan commented on frontend/src/components/Chatting/ChattingList.tsx
> +                  )}
추가로 padStart메서드를 활용하는 것이 좋겠네요

2021-09-06 04:24 UTC, shinsehantan commented on frontend/src/components/Chatting/ChattingList.tsx
> +  });
이대로 하면 제대로 정렬이 되질 않습니다ㅠ

2021-09-06 04:28 UTC, shinsehantan commented on frontend/src/components/Chatting/CurrentChatting.tsx
> +import RightSingleMessage from "./RightSingleMessage";
자동완성이 상대경로로 되었네요! 수정했습니다:)

2021-09-06 04:31 UTC, shinsehantan commented on frontend/src/components/Chatting/CurrentChatting.tsx
> +            }
sender와 receiver가 한 대화 채팅방 내에서도 계속 바뀔 예정이기 때문에 
변경될 응답에도 상대방 정보가 명확하게 담기지는 않을 것 같습니다. 

그래서 가장 첫 대화에서 sender이든 receiver이든 상관없이
내가 아닌 상대방을 찾아 해당 이미지만 가지고 오기 위해 위와 같은 로직을 사용했습니다.

2021-09-06 04:32 UTC, shinsehantan commented on frontend/src/components/DropDownMenu/DropDownMenu.tsx
> +      <LineDivider></LineDivider>
위쪽은 self closing을 써놓고, 아래는 그냥 놔두었네요... 수정했습니다~!

2021-09-06 04:34 UTC, shinsehantan commented on frontend/src/components/Header/Header.tsx
> +            onClick={() => setDropdownOpen(!dropdownOpen)}
이부분은 드롭다운 메뉴가 열렸을 때, 위에 화살표 모양 svg인 <UpArrow />가 함께 보이도록 처리해야해서 이렇게 진행했는데 혹시 더 좋은 방법이 있을까요?

2021-09-06 04:38 UTC, shinsehantan commented on frontend/src/components/MenuItemButton/MenuItemButton.tsx
> +const MenuItemButton = ({ contents, onClick, children, ...props }: Props) => {
`...props`가 `Button`으로 전달되고 있는데, `Inner`에 따로 넘겨주고 싶었기 때문에 따로 빼서 전달했습니다.

2021-09-06 04:40 UTC, shinsehantan commented on frontend/src/components/shared/Button/Button.tsx
> +    box-shadow: ${({ theme, hover }) => (hover ? theme.common.boxShadow.primary : "")};
none이 더 낫겠네요! 👍

2021-09-06 09:09 UTC, shinsehantan commented on frontend/src/components/Chatting/ChattingList.tsx
> +                  )}
추천해주신 것처럼 date 객체의 메서드를 사용하는 것은 좋은 것 같습니다.
하지만 padStart 메서드 등을 추가로 사용하는 등
필요한 형태로 가공해야 하기 때문에
아래와 같이 훨씬 복잡해지는 것 같습니다.

```
  const formatTimeToPassedTime = (time: string) => {
    const slicedTime = new Date(time.slice(0, -4));

    const year = slicedTime.getFullYear();
    const month = slicedTime.getMonth() + 1;
    const date = slicedTime.getDate();

    return toPassedTimeString(
      Number(year),
      Number(month.toString().padStart(2, "0")),
      Number(date.toString().padStart(2, "0"))
    );
  };
```

어떻게 생각하시나요?

2021-09-06 13:16 UTC, seojihwan commented on frontend/src/components/Chatting/ChattingList.tsx
> +                  )}
우선 toPassedTimeString이 인자로 숫자를 받고 있으니 padStart는 필요 없겠네요.
하지만 위의 코드와 아래코드를 봤을 때 아래 코드가 더 안전해 보이지 않나요?

뿐만아니라 위의 코드에서는 각 인자의 데이터가 어떤 형태인지, 데이터 형식을 봐야만 파악할 수 있을것같네요.

new Date(time.slice(0, -4)) 이부분은 formatTimeToPassedTime 이전에 처리(api응답을 가공) 해서 넘겨준다면 정렬할 떄에도 반복되는 코드를 줄일 수 있지 않을까요?

2021-09-06 13:35 UTC, seojihwan commented on frontend/src/components/Header/Header.tsx
> +            onClick={() => setDropdownOpen(!dropdownOpen)}
![image](https://user-images.githubusercontent.com/52202474/132225364-c4c614f5-e17a-4893-a8ca-ea2f9bc0b675.png)

DropdownMenu컴포넌트 내부에서 svg를 보여주면 되지않을까요?

2021-09-07 03:00 UTC, shinsehantan commented on frontend/src/components/Chatting/ChattingList.tsx
> +                  )}
Date 생성자로 문자열에서 날짜나 시간을 파싱하는 것은, 브라우저마다 동작이 다르고 차이가 존재하기 때문에 지양해야 한다고 알고 있는데, 더 안전하다는 것은 어떤 의미에서 안전하다는 것일까요?

2021-09-07 03:29 UTC, seojihwan commented on frontend/src/components/Chatting/ChattingList.tsx
> +                  )}
https://262.ecma-international.org/5.1/#sec-15.9.1.15
![image](https://user-images.githubusercontent.com/52202474/132279593-56d59b9f-0b1b-4d5c-82dd-ab36e9ad213f.png)

브라우저 지원률이나 스펙을 봣을때 호환성에 문제는 크게 없을것 같은데요? 어떻게 생각하시나요??
동작하지 않는 브라우저가 있었을까요?

Date Time String Format으로 맞춰주기만 한다면 서버에서 보내주는 데이터가 바뀌어도 index수정없이 유지할 수 있을 것 같네요.

2021-09-07 03:36 UTC, seojihwan commented on frontend/src/components/Chatting/ChattingList.tsx
> +                  )}
우선은 안전하다는 의미보다는 index로 접근하는 것을 피하고 의미를 명확하게 하자는 부분이 더 중요하다고 생각합니다.

2021-09-07 05:30 UTC, shinsehantan commented on frontend/src/components/Chatting/ChattingList.tsx
> +                  )}
호환성은 크게 문제가 없지만, 동작이 다를 수도 있다고 이해해서 언급했습니다.
<img width="660" alt="스크린샷 2021-09-07 오후 2 16 49" src="https://user-images.githubusercontent.com/67591151/132288082-772496cd-1b4f-433d-95a3-36e47aa82a0b.png">
아래처럼 두 가지 유틸로 분리해서 사용하니, 반복도 줄이고 꽤 명확해진 것 같은데 어떠신가요?
commit fbec46d016cbc8a059bf3540445e91b0f677d1a4

2021-09-07 05:43 UTC, shinsehantan commented on frontend/src/components/Header/Header.tsx
> +            onClick={() => setDropdownOpen(!dropdownOpen)}
화살표가 자꾸 아래로 묻혀서 드롭다운 컴포넌트 외부에서 작업했던 건데,
menuItem의 overflow 속성을 제거하니 올라오네요!
https://github.com/woowacourse-teams/2021-drop-the-code/pull/312/commits/2101d2a87d748f11b26ba11b086e09c34fadc95f

2021-09-07 06:37 UTC, seojihwan approved these changes
고생하셨습니다!

2021-09-07 06:37 UTC, merged