STOMP를 이용한 웹 소켓 연결 및 채팅 저장 기능 구현
woowacourse-teams/2021-drop-the-code pull request #316
Opened 2021-09-05 19:54 UTC by TaewanKimmmm

내일 하기로 한 연결 기능까지만 남겨놓고 인증 관련한 코드는 다 날렸습니다.

배경 지식 문서화 및 진행 상황은 다음과 같습니다.

# 웹 소켓 연결 방식

웹 소켓은 전이중 통신이므로, 연속적인 데이터 전송의 신뢰성을 보장하기 위해 Handshake 과정을 진행한다.

기존의 다른 TCP 기반의 프로토콜은 TCP layer에서의 Handshake를 통해 연결을 수립하는 반면, 

웹 소켓은 **`HTTP 요청 기반으로 Handshake 과정을 거쳐 연결을 수립`**한다.

웹 소켓은 연결을 수립하기 위해 `Upgrade 헤더`와 `Connection 헤더`를 포함하는 HTTP 요청을 보낸다.

![https://user-images.githubusercontent.com/50273712/129447412-30e32809-b1fe-4e95-9d7a-85553f3ab92b.png](https://user-images.githubusercontent.com/50273712/129447412-30e32809-b1fe-4e95-9d7a-85553f3ab92b.png)

연결이 수립되었을 때는 통상적인 상태 코드 200 대신, 웹 소켓 서버는 아래와 같이 101을 응답한다.

![https://user-images.githubusercontent.com/50273712/129448362-0ada9130-1181-4d3b-ac4b-33bd4130b00d.png](https://user-images.githubusercontent.com/50273712/129448362-0ada9130-1181-4d3b-ac4b-33bd4130b00d.png)

`101 Switching Protocols`: Handshake 요청 내용을 기반으로 다음부터 WebSocket으로 통신할 수 있다는 뜻이다. 

Handshake 과정을 통해 연결이 수립되면 응용 프로그램 계층 프로토콜이 HTTP에서 웹 소켓으로 업그레이드가 된다. 업그레이드가 되면 HTTP는 사용되지 않고, 웹 소켓 연결이 닫힐 때까지 두 끝 점에서 웹 소켓 프로토콜을 사용하여 데이터를 주고 받게 된다. 웹 소켓 연결은 주로 새로고침이나 창 닫기 등의 이벤트 발생 시 닫히게 된다.

# STOMP

스프링에서 웹 소켓을 사용할 때, 알아야 하는 또다른 프로토콜이 있다. STOMP 프로토콜이다.

STOMP는 `Simple Text Oriented Message Protocol`의 약자로 단순 텍스트 기반 메시징 프로토콜이다.

웹 소켓 프로토콜은 Text 또는 Binary 두 가지 유형의 메시지 타입은 정의하지만 메시지의 내용에
대해서는 정의하지 않는다. 따라서 STOMP라는 프로토콜을 서브 프로토콜로 사용한다. STOMP를 사용하게 되면 단순한 Binary, Text가 아닌 규격을 갖춘(format) message를 보낼 수 있다.

스프링은 웹 소켓 모듈을 통해서 STOMP를 제공하고 있다.

STOMP의 형식은 HTTP와 닮아 있다.

```
COMMAND

header1:value1
header2:value2

Body^@
```

COMMAND로 SEND 또는 SUBSCRIBE 명령을 사용하며, header와 value로 메시지의 수신 대상과 메시지에 대한 정보를 설명할 수 있다. 기존의 WebSocket만으로는 표현이 불가능한 형식이다.
이를 통해 STOMP 프로토콜은 Publisher-Subscriber를 지정하고, 중간에서 메시지 브로커 역할을 함으로써 특정 사용자에게만 메시지를 전송하는 기능 등을 가능하게 한다.

Publisher-Subscriber 패턴의 예시는 다음과 같다.

Client A는 다음과 같이 5번 채팅방에 대해 구독(SUBSCRIBE)을 걸어놓을 수 있다.

```
SUBSCRIBE
destination:/subscribe/chat/room/5
```

그리고 나서 Client B가 아래와 같이 채팅 메시지를 보낼 수 있다.

```
SEND
content-type:application/json
destination:/publish/chat
{"chatRoomId":5,"type":"MESSAGE","writer":"clientB"}
```

# 인증 관련 문제

웹 소켓 연결을 위한 HTTP 기반 HandShake 과정에서 Authentication을 하고자 하였습니다.

실제 구현해본 결과 콘솔에 찍었을 땐 아래 사진과 같이 헤더에 보이지만, 

![image](https://user-images.githubusercontent.com/50273712/132138840-bbeb9ce2-e384-4cd9-bde1-164a1bde6f1b.png)

네트워크 탭에서 확인했을 땐 Authorization 헤더가 존재하지 않았습니다.

![image](https://user-images.githubusercontent.com/50273712/132138869-a57505d3-ff6d-4413-a1e4-0a131ae88f6f.png)

왜일까 이유를 찾아보니 [STOMP authentication 관련 스프링 공식 문서](https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#websocket-stomp-authentication)에 따르면, 스프링은 기본적으로 HTTP 레벨에서 유저가 검증되었을 것이라고 생각하여 Authorization 헤더를 무시한다고 합니다.

그래도 일단 클라이언트에서 요청을 보내면서 심어놓았으니 꺼내는 방법이 있을 거라고 생각하여 방법을 찾았습니다.

Channel Interceptor를 구현하면 STOMP 헤더에 접근할 수 있고, jwt validator를 사용할 수 있습니다.

실제로 그렇게 구현했으나, 유효하지 않은 토큰에 대해 exception을 던져도 연결이 성공되었다는 101 status code를 반환합니다. Exception Handler에도 잡히지 않았습니다. 

다시 원점으로 돌아가서, STOMP CONNECT 프레임에 Authorization Header를 붙일 수 없을까?를 알아보았는데, 

[웹 소켓 헤더파 vs 헤더 반대파 전쟁터](https://github.com/whatwg/html/issues/3062)를 발견하게 되었습니다.

링크 내용을 요약하면,

A: 웹 소켓 핸드셰이크할 때 헤더 좀 붙이게 해주세요.. 

B: 나는 반대다. 웹소켓은 Connection에 대한 메타데이터 교환하라고 만든 프로토콜이 아니다. 그리고 헤더 추가하려면 Allow Header를 확인하는 등의 CORS 과정이 추가되어야 하는 비용이 있다.

A: 토큰을 쿼리 스트링으로 넘기는 수밖에 없게되는데, Authorization 헤더 쓰게 해주세요.

B: 그냥 jwt 토큰을 쿼리 스트링으로 넘겨서 써라. 클라이언트 단에서 소켓 주소로 접근할 수 없기 때문에 쿼리 스트링으로 토큰을 검사해도 충분하다.

다른 사람들: jwt 토큰을 쿼리 스트링으로 넘기라는 건 id랑 password를 넘기는 거나 다름없다. 무슨 소리냐.

# 결론

인증 방법은 추후 찾아보기로..

2021-09-05 19:54 UTC, jh8579 commented
Can one of the admins verify this patch?

2021-09-06 02:53 UTC, KJunseo requested changes
파피! 채팅 기능 구현하느라고 고생 많으셨네요
쉽지 않았을 것 같은데 정말 고생하셨습니다! 설명 적어주신 것도 잘 봤어요! 
몇 가지 코멘트 남겼습니다. 확인 후 다시 요청 주세요!
추가적으로 테스트 코드가 없는 것 같아요! 소켓관련은 저도 어떻게 하는지 모르지만, 그 부분을 제외한 부분들(모든 채팅 가져오기 등)은 테스트 코드를 작성할 수 있지 않을까요??

2021-09-06 02:53 UTC, KJunseo commented on backend/src/main/java/com/wootech/dropthecode/controller/RoomController.java
> +    public ResponseEntity<Void> createOrGet(@ModelAttribute @Valid RoomRequest roomRequest) {
생성과 가져오는 로직을 하나로 합치신 이유가 있을까요??
방을 생성할때는 POST & CREATED가 맞다고 생각하고, 방을 읽어올 때는 GET & OK가 맞다고 생각하는데, 2개를 하나의 메서드에서 처리하다보니 HTTP Method와 Status code가 어색한것 같다는 느낌을 받아서요!

2021-09-06 02:53 UTC, KJunseo commented on backend/src/main/java/com/wootech/dropthecode/dto/response/LatestChatResponse.java
> +    public static LatestChatResponse from(Member partner, Chat latestChat) {
매개변수가 여러개여서 `of()`를 쓰는 건 어떤가요?
```suggestion
    public static LatestChatResponse of(Member partner, Chat latestChat) {
```

2021-09-06 02:53 UTC, KJunseo commented on backend/src/main/java/com/wootech/dropthecode/repository/RoomRepository.java
> +    List<Room> findByTeacherIdOrStudentId(Long teacher_id, Long student_id);
사소하지만 `Optional<Room> findByTeacherIdAndStudentId`의 인자는 `studentId, teacherId`인데 `findByTeacherIdOrStudentId`의 인자는 `teacher_id, student_id`여서 통일하면 좋을 것 같네요!

또 `Optional<Room> findByTeacherIdAndStudentId`같은 경우 이름을 보면 teacherId가 먼저와야할 것 같은데, 인자로 studentId가 먼저 오고 있는 것 같아요!

2021-09-06 02:53 UTC, KJunseo commented on backend/src/main/java/com/wootech/dropthecode/service/ChattingService.java
> +    public List<LatestChatResponse> findAllLatestChats(Long id) {
Jpa 사용시 기본적으로 @Transactional(readOnly = true)가 붙어있어요(SimpleJpaRepository 참고)
그래서 이 메서드를 실행시 findById, findAllByMemberId 할때 마다 새로운 트랜잭션이 생성될 것 같은데, 메서드 레벨에 @Transactional(readOnly = true)를 둬서 하나의 트랜잭션으로 관리하는 것은 어떤가요?

2021-09-06 02:53 UTC, KJunseo commented on backend/src/main/java/com/wootech/dropthecode/service/RoomService.java
> +                                  .orElse(
orElse 사용시 room이 존재해도 항상 new Room이 실행될 것 같은데 orElseGet을 쓰는 건 어떤가요?

2021-09-06 02:53 UTC, KJunseo commented on backend/src/main/java/com/wootech/dropthecode/service/RoomService.java
> +    @Transactional
readOnly = true 옵션을 줘서 slave DB로 연결되게 하면 좋을 것 같아요!

2021-09-06 02:53 UTC, KJunseo commented on backend/src/main/java/com/wootech/dropthecode/service/RoomService.java
> +    public List<Room> findAllByMemberId(Long id) {
안붙여줘도 Transactional(readOnly = true)가 적용되겠지만, 붙여줄 거면 다 붙여줘서 통일되게 하는 것도 좋을 것 같네요!

2021-09-06 02:53 UTC, KJunseo commented on backend/src/main/java/com/wootech/dropthecode/service/ChattingService.java
> +    public void save(ChatRequest chatRequest) {
채팅을 하나 칠때마다 저장하는 것보다, 모아놨다가 batch insert같은 걸로 한 번에 저장하는게 어떤가 하는 생각이 들기도 하네요. 이건 나중에 최적화할때 얘기해봐도 좋을 것 같아요! 일단 생각나서 코멘트 남겨만 놓을게요!

2021-09-06 15:06 UTC, TaewanKimmmm commented on backend/src/main/java/com/wootech/dropthecode/controller/RoomController.java
> +    public ResponseEntity<Void> createOrGet(@ModelAttribute @Valid RoomRequest roomRequest) {
이 부분은 저도 고민을 많이 한 부분인데요! 현재 코드로 결정한 이유는 다음과 같습니다.

- 클라이언트 입장에서는 새로운 방을 생성하는지는 관심이 없고, 학생의 id와 선생님의 id를 가지고 있는 방 id만 받으면 됨 --> 없으면 만들고, 있으면 기존의 방 id를 넘김 --> createOrGet

- 학생의 id와 선생님의 id를 가지고 있는 채팅방 id는 유니크함 -> POST를 여러번 해도 서버의 응답 결과는 항상 같음 == 멱등성이 보장됨 --> GET으로 결정

다만 처음 방을 생성하는 경우보다 기존의 방을 조회하는 경우가 많을 테니 OK로 변경했습니다!

2021-09-06 15:10 UTC, TaewanKimmmm commented on backend/src/main/java/com/wootech/dropthecode/service/ChattingService.java
> +    public void save(ChatRequest chatRequest) {
말씀하신 것처럼 사용자가 채팅을 칠 때마다 DB에 insert하는 건 무리가 있을 것으로 생각합니다! 메세지 큐에 쌓아놨다가 데이터가 만료되기 전에 밀어 넣으면 될 것 같은데, 좀 더 알아봐야겠어요.

2021-09-06 15:27 UTC, TaewanKimmmm commented on backend/src/main/java/com/wootech/dropthecode/controller/ChattingController.java
> +    @MessageMapping("/messages")
다시 살펴봤는데 훨씬 이해가 빨리 되는 것 같네요!! 전적으로 동의합니다~

2021-09-06 15:47 UTC, TaewanKimmmm commented on backend/src/main/java/com/wootech/dropthecode/controller/ChattingController.java
> +    @MessageMapping("/messages")
RoomController로 로직을 이동시켰고, 코드는 다음과 같이 변경되었습니다.

```java
    @MessageMapping("/rooms/{roomId}")
    public void publish(@DestinationVariable Long roomId, @RequestBody @Valid ChatRequest chatRequest) {
        chattingService.save(roomId, chatRequest);
        simpMessagingTemplate.convertAndSend("/subscribe/rooms/" + roomId, chatRequest.getMessage());
    }
```

2021-09-07 02:25 UTC, hsik0225 approved these changes
채팅 적용하시느라 정말 고생많으셨습니다!
문서화도 잘해주셔서 공부할 때 많은 도움이 될 것 같아요 👍
나중에 궁금한 게 생기면 물어보러 갈게요 😄
이만 어푸하겠습니다 ~

2021-09-07 02:25 UTC, hsik0225 commented on backend/src/main/java/com/wootech/dropthecode/dto/response/ChatResponse.java
> +        this.senderImageUrl = senderImageUrl;
저희가 요청을 처리하기 위한 파라미터가 많이 필요해져서 필드가 많이 늘어났는데요.
해당 정보들을 그냥 필드로 가지고 있으니 점점 클래스가 커진 것 같고, 또 커질 것 같아요.
예를 들어 지금은 sender와 receiver 가 각각 `id`, `name`, `imageUrl`을 가지고 있는데 만약 나이도 필요하다고 하면 필드가 
각각 1개씩 총 2개 늘어나서 총 10개가 되겠죠.

관련 필드들을 묶어서 클래스로 만들어고, `@Embedded`로 사용하는 건 어떨까요?

[@Embedded 참고](https://velog.io/@conatuseus/JPA-%EC%9E%84%EB%B2%A0%EB%94%94%EB%93%9C-%ED%83%80%EC%9E%85embedded-type-8ak3ygq8wo)

아마 이건 저희 도메인 전체적으로 적용해야 할 것 같기도 하네요.
이슈로 따로 파는 것도 좋을 것 같네요.

2021-09-07 02:25 UTC, hsik0225 commented on backend/src/main/java/com/wootech/dropthecode/domain/chatting/Room.java
> +    private List<Chat> chats;
이거는 잘 몰라서 그런데 `List<Chat> chats = new ArrayList<>();`와 같이 초기화를 안해주고 있는데 괜찮나요?
NPE가 발생하지 않나요?

2021-09-07 11:14 UTC, jh8579 commented
retest this please

2021-09-07 12:13 UTC, jh8579 commented
retest this please

2021-09-07 12:33 UTC, jh8579 commented
retest this please

2021-09-07 13:53 UTC, TaewanKimmmm commented on backend/src/main/java/com/wootech/dropthecode/domain/chatting/Room.java
> +    private List<Chat> chats;
앗 초기화하는 게 좋을 것 같네요!

2021-09-07 13:55 UTC, jh8579 commented on backend/src/main/java/com/wootech/dropthecode/service/ChattingService.java
> +    public void save(ChatRequest chatRequest) {
제가 기억하기로 spring jpa는 batch insert를 지원하지 않는 걸로 알고있어서 고민을 해봐야겠네요

2021-09-07 14:03 UTC, jh8579 requested changes
Flyway 관련사항만 리뷰 드렸습니다!

2021-09-07 14:03 UTC, jh8579 commented on backend/src/main/java/com/wootech/dropthecode/domain/Member.java
> +    @OneToMany(mappedBy = "teacher", fetch = FetchType.LAZY, cascade = CascadeType.REMOVE)
좀 번거로운 부분일것 같은데 flyway 적용 이후에는 db 변경사항에 대해 직접 쿼리로 작성해줘야합니다 ㅜㅜ
`Member.java`, `Chat.java`, `Room.java` 도메인의 경우 테이블 생성, 외래키 설정, 컬럼 추가 등을 쿼리로 작성하여
[다음](https://github.com/woowacourse-teams/2021-drop-the-code/blob/dev/backend/src/main/resources/db/migration/V1__create.sql)과 같이 파일을 생성해야합니다.
파일명도 컨벤션이 있어서 [참조](https://bkim.tistory.com/2) `V2__insert_chat.sql`과 같은 파일을 생성해야 될거 같네요

2021-09-07 16:03 UTC, TaewanKimmmm commented on backend/src/main/java/com/wootech/dropthecode/domain/Member.java
> +    @OneToMany(mappedBy = "teacher", fetch = FetchType.LAZY, cascade = CascadeType.REMOVE)
오 안 그래도 DB 변경이 있어서 Flyway는 어떻게 해줘야 되나..생각하고 있었는데 알려주셔서 고맙습니다!!!!!!

2021-09-08 01:54 UTC, jh8579 approved these changes
sql까지 다 적용해주셨네요! 굳굳!
진짜 고생하셧습니다!

2021-09-08 04:40 UTC, KJunseo approved these changes
고생하셨습니다! 어푸!

2021-09-08 07:11 UTC, merged