채팅 기능 구현
woowacourse-teams/2021-drop-the-code pull request #340
Opened 2021-09-14 15:05 UTC by shinsehantan

- websocket, stompjs 사용한 실시간 채팅 기능 구현
- 보유한 채팅 목록 조회 기능 구현
- 단일 채팅 상세 조회 기능 구현

2021-09-14 15:05 UTC, jh8579 commented
Can one of the admins verify this patch?

2021-09-14 15:05 UTC, jh8579 commented
Can one of the admins verify this patch?

2021-09-15 13:20 UTC, seojihwan requested changes

2021-09-15 13:20 UTC, seojihwan commented on frontend/src/components/Chatting/CurrentChattingForm.tsx
> +
https://reactjs.org/docs/hooks-rules.html

Only Call Hooks at the Top Level 조건을 살펴볼까요?

2021-09-15 13:20 UTC, seojihwan commented on frontend/src/components/Chatting/CurrentChattingForm.tsx
> +  );
3항이 아니라 얼리 리턴을 활용하면 되지 않을까요?

2021-09-15 13:20 UTC, seojihwan commented on frontend/src/components/Chatting/CurrentChattingForm.tsx
> +  );
57번라인이후에 data가 항상존재할 것 같은데요 같이 확인하면 좋겟네요.

2021-09-15 13:20 UTC, seojihwan commented on frontend/src/components/FormProvider/FormProvider.tsx
>    };
이부분은 기존 유효성 검사 로직과 충돌할 수 있는 부분입니다.
폼 내부에 존재하는 각 인풋의 값들을 빈 값('') 으로 초기화 하지 않으면 문제가 발생할 수 있습니다.

2021-09-15 13:20 UTC, seojihwan commented on frontend/src/hooks/useChattingConnect.ts
> +    console.log("성공", response.data);
console.log 삭제해도 좋겟네요

2021-09-15 13:20 UTC, seojihwan commented on frontend/src/components/Chatting/CurrentChatting.tsx
>  };
3항이 여러번 걸쳐져서 받아들이기 어렵네요 얼리리턴을 활용할 수 있지 않을까요?

if (condition1) return <>1</>
if (condition2) return <>2</>
if (condition3) return <>3</>

2021-09-16 09:25 UTC, seojihwan commented
retest this please

2021-09-16 15:31 UTC, seojihwan commented
retest this please

2021-09-16 15:32 UTC, seojihwan approved these changes

2021-09-16 15:32 UTC, merged