SSE를 이용한 실시간 알림 & 유저별 알림 조회, 알림 읽음 처리
woowacourse-teams/2021-drop-the-code pull request #343
Opened 2021-09-15 19:07 UTC by KJunseo

### 구현 기능
- SSE(Server Sent Events)를 이용한 실시간 알림 기능 구현(로그인 한 상태면 실시간 웹 알림)
  - [선생님 입장]
    - 새로운 리뷰 요청이 온 경우
    - 리뷰 상태가 FINISHED가 된 경우 피드백을 확인하라는 알림
  - [학생 입장]
    - 리뷰 요청이 거절된 경우
    - 리뷰 요청이 수락된 경우
    - 선생님이 리뷰를 완료한 경우
- 로그인 한 유저의 전체 알림 목록 조회
- 읽지 않은 알림 읽음 처리

### 보완할 것 
- sse 연결 테스트를 어떻게 해야할지 아직 잘 모르겠어서 추후에 추가하겠습니다. 조금 찾아봤는데, rest assured에서는 지원하지 않는 것 같습니다.
- 읽지 않은 채팅이 있는 경우도 알림을 보내주면 좋을 것 같습니다. 이 경우는 채팅 하나하나당 모두 알림 테이블에 저장하기 보다는 다른 방식을 생각해보는 게 좋을 것 같습니다.

<hr>

## 문서화는 내일 중으로 완료하겠습니다!

2021-09-15 19:07 UTC, jh8579 commented
Can one of the admins verify this patch?

2021-10-06 10:38 UTC, jh8579 requested changes
리뷰가 너무 늦었네요
일단 궁금한 부분들만 질문 남겼습니다!

2021-10-06 10:38 UTC, jh8579 commented on backend/src/main/java/com/wootech/dropthecode/service/NotificationService.java
> +        sendToClient(emitter, id, "EventStream Created. [userId=" + userId + "]");
더미 이벤트를 전송하지 않으면 에러가 발생하는 이유가 뭔가요?

2021-10-06 10:38 UTC, jh8579 commented on backend/src/main/java/com/wootech/dropthecode/repository/EmitterRepository.java
> +    private final Map<String, Object> eventCache = new ConcurrentHashMap<>();
운영 서버는 서버 이중화가 되어 있는데  이중화 구성일 때 이슈가 없을까요?

2021-10-08 07:37 UTC, KJunseo commented on backend/src/main/java/com/wootech/dropthecode/service/NotificationService.java
> +        sendToClient(emitter, id, "EventStream Created. [userId=" + userId + "]");
클라이언트에서 EventSteam이 생성된 이후 서버에서 1개의 Event도 전송하지 않았을 경우 503에러가 발생해요. 그래서 그런경우를 방지하기 위해 일단 더미 이벤트를 보내게 했습니다!

2021-10-08 08:02 UTC, KJunseo commented on backend/src/main/java/com/wootech/dropthecode/repository/EmitterRepository.java
> +    private final Map<String, Object> eventCache = new ConcurrentHashMap<>();
음.. 로그인을 한 이후의 요청이 다른 WAS로 가게 된다면 아마 실시간 알림이 발생하지 않을 것 같네요..ㅠㅠ

https://medium.com/javarevisited/building-scalable-facebook-like-notification-using-server-sent-event-and-redis-9d0944dee618

이 글처럼 redis의 pub/sub 기능?을 사용하면 될 것 같은데 뭔지 몰라서 알아봐야겠네요. 시간이 걸릴것 같은데 다른 issue로 분리해서 담당해도 좋을것 같다는 생각이드네요

2021-10-20 06:02 UTC, hsik0225 approved these changes
리뷰가 너무 늦었네요.
제가 아직 SSE에 대한 학습이 부족해서, 리뷰는 추후 공부 후 다시 에어와 이야기하겠습니다.
어프로브할게요.
고생하셨습니다!

2021-10-20 07:00 UTC, merged